# -*- coding: utf-8 -*-
"""PM-10 AND PM2.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4ot0CiM0Qcm69VXWx9PbQeoX17MMd2C
"""

# ============================================================
# 1) Carga de datos + Feature Engineering
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# --- Config ---
FILE = "dateWr.xlsx"       # súbelo en Colab (o cambia la ruta)
SHEET = "Hoja1"

# --- Carga ---
df = pd.read_excel(FILE, sheet_name=SHEET)
df.columns = [c.strip().replace(" ", "_").replace("-", "_").replace(".", "") for c in df.columns]

# Asegurar datetime
df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce")

# Coordenadas si existen (limpiar símbolo ° y a float)
for col in ["LATITUD_N","LONGITUD_O"]:
    if col in df.columns:
        df[col] = df[col].astype(str).str.replace("°","", regex=False)
        df[col] = pd.to_numeric(df[col], errors="coerce")
# Si LONGITUD_O es oeste, déjala negativa (si ya viene negativa, no cambia)
if "LONGITUD_O" in df.columns:
    df["LONGITUD_O"] = df["LONGITUD_O"].apply(lambda x: -abs(x) if pd.notna(x) else x)

# Variables de tiempo
df["month"] = df["DATE"].dt.month
df["dow"]   = df["DATE"].dt.dayofweek

# Elimina filas sin target ni PM_10
df = df.dropna(subset=["PM_25","PM_10"]).copy()

# Split temporal simple (80/20 por orden cronológico)
df = df.sort_values("DATE").reset_index(drop=True)
split = int(len(df)*0.8)
train_df, test_df = df.iloc[:split].copy(), df.iloc[split:].copy()

# Definir columnas numéricas/categóricas disponibles
num_cols = [c for c in ["PM_10","Temp_C","Presion__mmHg","LATITUD_N","LONGITUD_O","month","dow"] if c in df.columns]
cat_cols = [c for c in ["STATION"] if c in df.columns]

X_train = train_df[num_cols + cat_cols]
y_train = train_df["PM_25"]
X_test  = test_df[num_cols + cat_cols]
y_test  = test_df["PM_25"]

# Preprocesamiento común
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

numeric_tf = Pipeline(steps=[
    ("imp", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])
categorical_tf = Pipeline(steps=[
    ("imp", SimpleImputer(strategy="most_frequent")),
    ("oh",  OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_tf, num_cols),
        ("cat", categorical_tf, cat_cols)
])

df.head()

"""**REGRESIÓN: Lineal vs RandomForest vs XGBoost**"""

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

def eval_reg(y_true, y_pred, nombre="Modelo"):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) # Removed squared=False
    r2   = r2_score(y_true, y_pred)
    print(f"{nombre} -> MAE: {mae:.3f} | RMSE: {rmse:.3f} | R²: {r2:.3f}")
    return mae, rmse, r2

"""**Regresión Lineal**"""

lin_pipe = Pipeline(steps=[("prep", preprocess),
                          ("model", LinearRegression())])
lin_pipe.fit(X_train, y_train)
pred_lin = lin_pipe.predict(X_test)
eval_reg(y_test, pred_lin, "Regresión Lineal")

lin_pipe = Pipeline(steps=[("prep", preprocess),
                          ("model", LinearRegression())])
lin_pipe.fit(X_train, y_train)
pred_lin = lin_pipe.predict(X_test)
eval_reg(y_test, pred_lin, "Regresión Lineal")

"""**Random Forest Regression**"""

rf_pipe = Pipeline(steps=[("prep", preprocess),
                         ("model", RandomForestRegressor(random_state=42))])
rf_pipe.fit(X_train, y_train)
pred_rf = rf_pipe.predict(X_test)
eval_reg(y_test, pred_rf, "Random Forest")

"""**XGBoost Regression**"""

xgb_pipe = Pipeline(steps=[("prep", preprocess),
                          ("model", XGBRegressor(random_state=42))])
xgb_pipe.fit(X_train, y_train)
pred_xgb = xgb_pipe.predict(X_test)
eval_reg(y_test, pred_xgb, "XGBoost")

"""**Comparison of Models**"""

# You can compare the MAE, RMSE, and R² values printed above for each model
# to see which one performed best on the test data.

"""**Gráfico Observado vs Predicho (mejor modelo a ojo: XGB)**"""

plt.figure(figsize=(5,5))
plt.scatter(y_test, pred_xgb, alpha=0.6)
plt.xlabel("PM2.5 observado (µg/m³)")
plt.ylabel("PM2.5 predicho (µg/m³)")
plt.title("Regresión PM2.5 - XGBoost")
plt.plot([y_test.min(), y_test.max()],[y_test.min(), y_test.max()], lw=2)  # línea 1:1
plt.show()

"""**CLASIFICACIÓN: binaria (OMS 15 µg/m³) y multiclase (≤15, 15–25, >25)**"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

"""**Etiqueta BINARIA (OMS 2021 24h: 15 µg/m³)**"""

train_df["pm25_alert"] = (train_df["PM_25"] > 15).astype(int)
test_df["pm25_alert"]  = (test_df["PM_25"]  > 15).astype(int)

Xc_train = train_df[num_cols + cat_cols]
yc_train = train_df["pm25_alert"]
Xc_test  = test_df[num_cols + cat_cols]
yc_test  = test_df["pm25_alert"]

clf_lr = Pipeline(steps=[("prep", preprocess),
                        ("model", LogisticRegression(max_iter=2000, class_weight="balanced"))])
clf_lr.fit(Xc_train, yc_train)
pred_lr = clf_lr.predict(Xc_test)

print("=== Clasificación binaria (OMS 15 µg/m³) - Regresión Logística ===")
print(classification_report(yc_test, pred_lr, digits=3))
ConfusionMatrixDisplay(confusion_matrix(yc_test, pred_lr)).plot()
plt.title("Matriz de confusión - Binaria (LR)")
plt.show()

"""**Random Forest Classifier (binaria)**"""

clf_rf = Pipeline(steps=[("prep", preprocess),
                        ("model", RandomForestClassifier(
                            n_estimators=400, random_state=42, class_weight="balanced"))])
clf_rf.fit(Xc_train, yc_train)
pred_rf_c = clf_rf.predict(Xc_test)

print("=== Clasificación binaria (OMS 15 µg/m³) - Random Forest ===")
print(classification_report(yc_test, pred_rf_c, digits=3))
ConfusionMatrixDisplay(confusion_matrix(yc_test, pred_rf_c)).plot()
plt.title("Matriz de confusión - Binaria (RF)")
plt.show()

"""**Etiqueta MULTICLASE: 0: ≤15, 1: (15,25], 2: >25**"""

def bucket_pm25(v):
    if v <= 15: return 0
    elif v <= 25: return 1
    else: return 2

train_df["pm25_bucket"] = train_df["PM_25"].apply(bucket_pm25)
test_df["pm25_bucket"]  = test_df["PM_25"].apply(bucket_pm25)

Xm_train = train_df[num_cols + cat_cols]
ym_train = train_df["pm25_bucket"]
Xm_test  = test_df[num_cols + cat_cols]
ym_test  = test_df["pm25_bucket"]

clf_mc = Pipeline(steps=[("prep", preprocess),
                        ("model", RandomForestClassifier(
                            n_estimators=500, random_state=42, class_weight="balanced"))])
clf_mc.fit(Xm_train, ym_train)
pred_mc = clf_mc.predict(Xm_test)

print("=== Clasificación multiclase (≤15, 15–25, >25) - RF ===")
print(classification_report(ym_test, pred_mc, digits=3))
ConfusionMatrixDisplay(confusion_matrix(ym_test, pred_mc)).plot()
plt.title("Matriz de confusión - Multiclase (RF)")
plt.show()

"""**Utilidades: Importancias de variables (árboles) y SHAP opcional**"""

# Importancias del Random Forest de REGRESIÓN
rf_model = rf_pipe.named_steps["model"]
# Para conocer los nombres tras OneHot: usa el transformador
prep = rf_pipe.named_steps["prep"]
feature_names = []

# columnas numéricas tal cual
feature_names += num_cols
# columnas categóricas (one-hot)
if len(cat_cols) > 0:
    oh = prep.named_transformers_["cat"].named_steps["oh"]
    cats = oh.get_feature_names_out(cat_cols).tolist()
    feature_names += cats

importances = rf_model.feature_importances_
imp_df = pd.DataFrame({"feature": feature_names, "importance": importances}).sort_values("importance", ascending=False)
print("Importancias (RF Regresión):")
print(imp_df.head(15))

plt.figure(figsize=(7,5))
sns.barplot(data=imp_df.head(12), x="importance", y="feature")
plt.title("Top-12 features - RF (Regresión PM2.5)")
plt.tight_layout()
plt.show()