# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtogH_6_XOnDtYVwZu3tlRpZh0YIOlmx
"""



"""**Análisis Predictivo**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegressio

import pandas as pd
df = pd.read_excel('dateWr.xlsx')
df.head()

"""**Normalizar series**"""

df.columns = [c.strip().replace(" ", "_").replace("-", "_").replace(".", "") for c in df.columns]
df.info()
df.head()

"""**Limpieza y Feature Engineering**"""

import re

def clean_degrees(coord_str):
    # Use regex to find the numeric part of the coordinate string
    match = re.search(r'[-+]?\d*\.?\d+', str(coord_str))
    if match:
        return float(match.group(0))
    return None # Return None for values that cannot be parsed

df["LATITUD_N"] = df["LATITUD_N"].apply(clean_degrees)
df["LONGITUD_O"] = df["LONGITUD_O"].apply(clean_degrees)

# Display the first few rows to check the result
display(df.head())

"""**Variables Temporales**"""

df["month"] = df["DATE"].dt.month
df["dow"]   = df["DATE"].dt.dayofweek

"""**Agregación diaria por estación**"""

daily = (df
         .set_index("DATE")
         .groupby([pd.Grouper(freq="D"), "STATION"])
         [["PM_10","PM_25","Temp_C","Presion__mmHg","LATITUD_N","LONGITUD_O"]]
         .mean()
         .reset_index()
        )

"""**Eliminar filas con PM faltante**"""

daily = daily.dropna(subset=["PM_10","PM_25"])
daily = daily.sort_values(["STATION","DATE"]).reset_index(drop=True)

daily.shape
daily.head()

"""**Modelo de Regresión (PM2.5)**"""

num_cols = ["PM_10","Temp_C","Presion__mmHg","LATITUD_N","LONGITUD_O","month","dow"]
cat_cols = ["STATION"]

X = daily[num_cols + cat_cols]
y = daily["PM_25"]

"""**Split temporal (train = 80%, test = 20%)**"""

split = int(len(daily) * 0.8)
X_train, X_test = X.iloc[:split], X.iloc[split:]
y_train, y_test = y.iloc[:split], y.iloc[split:]

"""**Procesamiento**"""

split = int(len(daily) * 0.8)
X_train, X_test = X.iloc[:split], X.iloc[split:]
y_train, y_test = y.iloc[:split], y.iloc[split:]

"""**Random Forest Regressor**"""

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor

# Define preprocessing for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create preprocessor object
preprocess = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, num_cols),
        ('cat', categorical_transformer, cat_cols)
    ])

# Drop rows with NaN values in y_train and corresponding rows in X_train
nan_mask = y_train.isna()
X_train = X_train[~nan_mask]
y_train = y_train[~nan_mask]


reg_pipe = Pipeline(steps=[("preprocess", preprocess),
                          ("model", RandomForestRegressor(n_estimators=300, random_state=42))])
reg_pipe.fit(X_train, y_train)
y_pred = reg_pipe.predict(X_test)

"""** Métricas**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Drop rows with NaN values in y_test and corresponding rows in X_test
nan_mask_test = y_test.isna()
X_test = X_test[~nan_mask_test]
y_test = y_test[~nan_mask_test]

# Regenerate y_pred using the filtered X_test
y_pred = reg_pipe.predict(X_test)

print("\n📊 MÉTRICAS REGRESIÓN PM2.5")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", mean_squared_error(y_test, y_pred, squared=False))
print("R2:", r2_score(y_test, y_pred))

"""**Gráfico observado vs predicho**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))

# Valores observados vs predichos (dispersión)
plt.scatter(y_test, y_pred, alpha=0.6, color="blue", label="PM2.5 predicho")

# Línea de referencia (y=x)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red", linestyle="--", label="PM2.5 observado")

plt.xlabel("PM2.5 observado")
plt.ylabel("PM2.5 predicho")
plt.title("Regresión PM2.5 - Random Forest")
plt.legend()
plt.show()

"""**Modelo de Regresión (PM10)**"""

# Define features (X) and target (y) for PM10 regression
X_pm10 = daily[num_cols + cat_cols]
y_pm10 = daily["PM_10"]

"""**Split temporal (train = 80%, test = 20%) for PM10**"""

split_pm10 = int(len(daily) * 0.8)
X_train_pm10, X_test_pm10 = X_pm10.iloc[:split_pm10], X_pm10.iloc[split_pm10:]
y_train_pm10, y_test_pm10 = y_pm10.iloc[:split_pm10], y_pm10.iloc[split_pm10:]

"""**Random Forest Regressor for PM10**"""

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
import numpy as np # Import numpy for sqrt

# Define preprocessing for numerical and categorical features (reuse if applicable)
# Assuming the same preprocessing steps are suitable for PM10

# Create preprocessor object (reuse if applicable)
# preprocess is already defined in a previous cell and should be suitable

# Drop rows with NaN values in y_train_pm10 and corresponding rows in X_train_pm10
nan_mask_pm10 = y_train_pm10.isna()
X_train_pm10 = X_train_pm10[~nan_mask_pm10]
y_train_pm10 = y_train_pm10[~nan_mask_pm10]

reg_pipe_pm10 = Pipeline(steps=[("preprocess", preprocess),
                               ("model", RandomForestRegressor(n_estimators=300, random_state=42))])
reg_pipe_pm10.fit(X_train_pm10, y_train_pm10)
y_pred_pm10 = reg_pipe_pm10.predict(X_test_pm10)

"""** Métricas (PM10)**"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Drop rows with NaN values in y_test_pm10 and corresponding rows in X_test_pm10
nan_mask_test_pm10 = y_test_pm10.isna()
X_test_pm10 = X_test_pm10[~nan_mask_test_pm10]
y_test_pm10 = y_test_pm10[~nan_mask_test_pm10]

# Regenerate y_pred_pm10 using the filtered X_test_pm10
y_pred_pm10 = reg_pipe_pm10.predict(X_test_pm10)

print("\n📊 MÉTRICAS REGRESIÓN PM10")
print("MAE:", mean_absolute_error(y_test_pm10, y_pred_pm10))
mse_pm10 = mean_squared_error(y_test_pm10, y_pred_pm10)
print("RMSE:", np.sqrt(mse_pm10))
print("R2:", r2_score(y_test_pm10, y_pred_pm10))

"""**Gráfico observado vs predicho (PM10)**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))

# Valores observados vs predichos (dispersión)
plt.scatter(y_test_pm10, y_pred_pm10, alpha=0.6, color="blue", label="PM10 predicho")

# Línea de referencia (y=x)
plt.plot([y_test_pm10.min(), y_test_pm10.max()],
         [y_test_pm10.min(), y_test_pm10.max()],
         color="red", linestyle="--", label="PM10 observado")

plt.xlabel("PM10 observado")
plt.ylabel("PM10 predicho")
plt.title("Regresión PM10 - Random Forest")
plt.legend()
plt.show()

"""**Clasificación (Alerta OMS PM2.5 > 15 µg/m³)**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer


daily["pm25_alert"] = (daily["PM_25"] > 15).astype(int)

Xc = daily[num_cols + cat_cols]
yc = daily["pm25_alert"]

split = int(len(daily) * 0.8)
Xc_train, Xc_test = Xc.iloc[:split], Xc.iloc[split:]
yc_train, yc_test = yc.iloc[:split], yc.iloc[split:]

clf_pipe = Pipeline(steps=[("preprocess", preprocess),
                          ("model", LogisticRegression(max_iter=1000))])
clf_pipe.fit(Xc_train, yc_train)
yc_pred = clf_pipe.predict(Xc_test)

print("\n📊 REPORTE CLASIFICACIÓN ALERTA OMS")
print(classification_report(yc_test, yc_pred))
print("Matriz de confusión:\n", confusion_matrix(yc_test, yc_pred))

"""**Gráfico serie temporal**"""

plt.figure(figsize=(12,5))
plt.plot(daily["DATE"], daily["PM_25"], label="PM2.5 observado")
plt.axhline(15, color="red", linestyle="--", label="Umbral OMS 2021 (15 µg/m³)")
plt.legend()
plt.title("Serie temporal PM2.5")
plt.xlabel("Fecha")
plt.ylabel("PM2.5 (µg/m³)")
plt.show()