# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBtE0cH-blEXW9CiXW0Xa114--9DXL6H

## PROYECTO TALENTO TECH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel('dateWr.xlsx')
df.head()

"""Exploración **inicial**"""

df.shape

df.describe()

df.info()

"""**LIMPIEZA DE LOS DATOS **"""



df_cleaned = df.dropna()
print("Shape of the DataFrame after removing rows with missing values:")
display(df_cleaned.shape)

df.head()

"""**Distribución de PM10 y PM2.5**"""

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.histplot(df["PM-10"], bins=30, kde=True, color="skyblue")
plt.title("Distribución PM-10")

plt.subplot(1,2,2)
sns.histplot(df["PM-2.5"], bins=30, kde=True, color="orange")
plt.title("Distribución PM-2.5")

plt.show()

"""**Boxplots por estación**"""

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.boxplot(data=df, x="STATION", y="PM-10")
plt.title("PM-10 por estación")

plt.subplot(1,2,2)
sns.boxplot(data=df, x="STATION", y="PM-2.5")
plt.title("PM-2.5 por estación")

plt.show()

"""**Correlaciones**"""

plt.figure(figsize=(8,6))
corr = df[["PM-10","PM-2.5","Temp C","Presion- mmHg"]].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm", vmin=-1, vmax=1)
plt.title("Matriz de correlación")
plt.show()

"""**Relación PM-10 vs PM-2.5**"""

plt.figure(figsize=(6,5))
sns.scatterplot(data=df, x="PM-10", y="PM-2.5", hue="STATION", palette="tab10", alpha=0.7)
plt.title("Relación entre PM-10 y PM-2.5 por estación")
plt.show()

"""**Valores atípicos (outliers)**"""

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.boxplot(y=df["PM-10"], color="skyblue")
plt.title("Outliers PM-10")

plt.subplot(1,2,2)
sns.boxplot(y=df["PM-2.5"], color="orange")
plt.title("Outliers PM-2.5")

plt.show()